//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papersPlease.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurnal
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datePost { get; set; }
        public Nullable<int> idVid { get; set; }
        public string nickName { get; set; }
        public Nullable<bool> paspots { get; set; }
        public Nullable<int> age { get; set; }
        public string service { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    
        public virtual Vid Vid { get; set; }
    }
}
